# Generated by Django 5.0.2 on 2024-03-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_technology_customusergrades_customuserrankings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='customusertoimage',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='customusertotechnology',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customusertotechnology',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='customusertotechnology',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='technologies',
            field=models.ManyToManyField(to='api.technology'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.ManyToManyField(to='api.profileimage'),
        ),
        migrations.DeleteModel(
            name='CustomUserRankings',
        ),
        migrations.DeleteModel(
            name='CustomUserToImage',
        ),
        migrations.DeleteModel(
            name='CustomUserToTechnology',
        ),
    ]
