# Generated by Django 5.0.2 on 2024-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_code_snippet_customuser_code_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(default='I love CoDates', max_length=255),
            preserve_default=False,
        ),
    ]
