# Generated by Django 5.0.2 on 2024-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cluster',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_theme',
            field=models.CharField(choices=[('atom-one-dark', 'Atom One Dark'), ('gradient-light', 'Gradient Light'), ('tomorrow-night-blue', 'Tomorrow Night Blue'), ('atom-one-dark-reasonable', 'Atom One Dark Reasonable'), ('tokyo-night-dark', 'Tokyo Night Dark'), ('devibeans', 'Devibeans'), ('kimbie-light', 'Kimbie Light'), ('lightfair', 'Lightfair'), ('stackoverflow-light', 'Stackoverflow Light'), ('a11y-light', 'A11y Light'), ('tomorrow-night-bright', 'Tomorrow Night Bright'), ('ir-black', 'IR Black'), ('arta', 'Arta'), ('srcery', 'Srcery'), ('night-owl', 'Night Owl'), ('dark', 'Dark'), ('tokyo-night-light', 'Tokyo Night Light'), ('ascetic', 'Ascetic'), ('arduino-light', 'Arduino Light'), ('qtcreator-dark', 'Qtcreator Dark'), ('isbl-editor-dark', 'ISBL Editor Dark'), ('nnfx-dark', 'NNFX Dark'), ('paraiso-light', 'Paraiso Light'), ('vs2015', 'VS 2015'), ('nord', 'Nord'), ('idea', 'Idea'), ('shades-of-purple', 'Shades Of Purple'), ('pojoaque', 'Pojoaque'), ('color-brewer', 'Color Brewer'), ('xt256', 'XT256'), ('nnfx-light', 'NNFX Light'), ('mono-blue', 'Mono Blue'), ('vs', 'VS'), ('felipec', 'Felipec'), ('docco', 'Docco'), ('purebasic', 'Purebasic'), ('stackoverflow-dark', 'Stackoverflow Dark'), ('brown-paper', 'Brown Paper'), ('hybrid', 'Hybrid'), ('panda-syntax-dark', 'Panda Syntax Dark'), ('kimbie-dark', 'Kimbie Dark'), ('googlecode', 'Google Code'), ('rainbow', 'Rainbow'), ('panda-syntax-light', 'Panda Syntax Light'), ('gml', 'GML'), ('github-dark-dimmed', 'Github Dark Dimmed'), ('monokai-sublime', 'Monokai Sublime'), ('routeros', 'Routeros'), ('isbl-editor-light', 'ISBL Editor Light'), ('sunburst', 'Sunburst'), ('default', 'Default'), ('intellij-light', 'Intellij Light'), ('far', 'Far'), ('lioshi', 'Lioshi'), ('school-book', 'School Book'), ('codepen-embed', 'Codepen Embed'), ('atom-one-light', 'Atom One Light'), ('grayscale', 'Grayscale'), ('agate', 'Agate'), ('qtcreator-light', 'Qtcreator Light'), ('gradient-dark', 'Gradient Dark'), ('obsidian', 'Obsidian'), ('xcode', 'Xcode'), ('foundation', 'Foundation'), ('androidstudio', 'Android Studio'), ('monokai', 'Monokai'), ('a11y-dark', 'A11y Dark'), ('magula', 'Magula'), ('an-old-hope', 'An Old Hope'), ('paraiso-dark', 'Paraiso Dark'), ('github-dark', 'Github Dark'), ('github', 'Github')], max_length=255),
        ),
    ]
