# Generated by Django 5.0.2 on 2024-03-18 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_code_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code_theme',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('idea', 'Idea'), ('intellij-light', 'Intellij Light'), ('paraiso-light', 'Paraiso Light'), ('stackoverflow-dark', 'Stackoverflow Dark'), ('foundation', 'Foundation'), ('xt256', 'XT256'), ('isbl-editor-light', 'ISBL Editor Light'), ('monokai-sublime', 'Monokai Sublime'), ('tokyo-night-light', 'Tokyo Night Light'), ('night-owl', 'Night Owl'), ('school-book', 'School Book'), ('monokai', 'Monokai'), ('grayscale', 'Grayscale'), ('qtcreator-dark', 'Qtcreator Dark'), ('codepen-embed', 'Codepen Embed'), ('qtcreator-light', 'Qtcreator Light'), ('agate', 'Agate'), ('rainbow', 'Rainbow'), ('ir-black', 'IR Black'), ('paraiso-dark', 'Paraiso Dark'), ('purebasic', 'Purebasic'), ('atom-one-light', 'Atom One Light'), ('atom-one-dark', 'Atom One Dark'), ('tomorrow-night-blue', 'Tomorrow Night Blue'), ('sunburst', 'Sunburst'), ('lioshi', 'Lioshi'), ('a11y-light', 'A11y Light'), ('color-brewer', 'Color Brewer'), ('panda-syntax-light', 'Panda Syntax Light'), ('a11y-dark', 'A11y Dark'), ('panda-syntax-dark', 'Panda Syntax Dark'), ('docco', 'Docco'), ('shades-of-purple', 'Shades Of Purple'), ('kimbie-light', 'Kimbie Light'), ('isbl-editor-dark', 'ISBL Editor Dark'), ('routeros', 'Routeros'), ('felipec', 'Felipec'), ('nnfx-dark', 'NNFX Dark'), ('an-old-hope', 'An Old Hope'), ('brown-paper', 'Brown Paper'), ('tomorrow-night-bright', 'Tomorrow Night Bright'), ('gradient-dark', 'Gradient Dark'), ('github-dark-dimmed', 'Github Dark Dimmed'), ('dark', 'Dark'), ('magula', 'Magula'), ('mono-blue', 'Mono Blue'), ('stackoverflow-light', 'Stackoverflow Light'), ('gml', 'GML'), ('nnfx-light', 'NNFX Light'), ('arta', 'Arta'), ('lightfair', 'Lightfair'), ('default', 'Default'), ('androidstudio', 'Android Studio'), ('github', 'Github'), ('far', 'Far'), ('gradient-light', 'Gradient Light'), ('atom-one-dark-reasonable', 'Atom One Dark Reasonable'), ('pojoaque', 'Pojoaque'), ('vs2015', 'VS 2015'), ('tokyo-night-dark', 'Tokyo Night Dark'), ('obsidian', 'Obsidian'), ('srcery', 'Srcery'), ('devibeans', 'Devibeans'), ('xcode', 'Xcode'), ('nord', 'Nord'), ('github-dark', 'Github Dark'), ('vs', 'VS'), ('kimbie-dark', 'Kimbie Dark'), ('googlecode', 'Google Code'), ('arduino-light', 'Arduino Light'), ('ascetic', 'Ascetic')], max_length=255),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
