# Generated by Django 5.0.2 on 2024-03-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_code_theme_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_id', to='api.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_theme',
            field=models.CharField(choices=[('xcode', 'Xcode'), ('nnfx-light', 'NNFX Light'), ('ir-black', 'IR Black'), ('intellij-light', 'Intellij Light'), ('ascetic', 'Ascetic'), ('arduino-light', 'Arduino Light'), ('qtcreator-dark', 'Qtcreator Dark'), ('googlecode', 'Google Code'), ('magula', 'Magula'), ('idea', 'Idea'), ('kimbie-dark', 'Kimbie Dark'), ('far', 'Far'), ('kimbie-light', 'Kimbie Light'), ('hybrid', 'Hybrid'), ('an-old-hope', 'An Old Hope'), ('atom-one-dark', 'Atom One Dark'), ('mono-blue', 'Mono Blue'), ('school-book', 'School Book'), ('github', 'Github'), ('purebasic', 'Purebasic'), ('sunburst', 'Sunburst'), ('stackoverflow-light', 'Stackoverflow Light'), ('tomorrow-night-bright', 'Tomorrow Night Bright'), ('srcery', 'Srcery'), ('obsidian', 'Obsidian'), ('foundation', 'Foundation'), ('xt256', 'XT256'), ('vs2015', 'VS 2015'), ('codepen-embed', 'Codepen Embed'), ('tokyo-night-dark', 'Tokyo Night Dark'), ('qtcreator-light', 'Qtcreator Light'), ('lightfair', 'Lightfair'), ('panda-syntax-light', 'Panda Syntax Light'), ('arta', 'Arta'), ('devibeans', 'Devibeans'), ('agate', 'Agate'), ('gml', 'GML'), ('gradient-dark', 'Gradient Dark'), ('a11y-dark', 'A11y Dark'), ('grayscale', 'Grayscale'), ('gradient-light', 'Gradient Light'), ('github-dark-dimmed', 'Github Dark Dimmed'), ('routeros', 'Routeros'), ('lioshi', 'Lioshi'), ('atom-one-light', 'Atom One Light'), ('github-dark', 'Github Dark'), ('tokyo-night-light', 'Tokyo Night Light'), ('panda-syntax-dark', 'Panda Syntax Dark'), ('isbl-editor-light', 'ISBL Editor Light'), ('brown-paper', 'Brown Paper'), ('a11y-light', 'A11y Light'), ('shades-of-purple', 'Shades Of Purple'), ('felipec', 'Felipec'), ('monokai-sublime', 'Monokai Sublime'), ('tomorrow-night-blue', 'Tomorrow Night Blue'), ('rainbow', 'Rainbow'), ('pojoaque', 'Pojoaque'), ('paraiso-dark', 'Paraiso Dark'), ('atom-one-dark-reasonable', 'Atom One Dark Reasonable'), ('nnfx-dark', 'NNFX Dark'), ('docco', 'Docco'), ('androidstudio', 'Android Studio'), ('default', 'Default'), ('paraiso-light', 'Paraiso Light'), ('stackoverflow-dark', 'Stackoverflow Dark'), ('night-owl', 'Night Owl'), ('nord', 'Nord'), ('color-brewer', 'Color Brewer'), ('monokai', 'Monokai'), ('dark', 'Dark'), ('vs', 'VS'), ('isbl-editor-dark', 'ISBL Editor Dark')], max_length=255),
        ),
    ]
