# Generated by Django 5.0.2 on 2024-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_message_chat_alter_customuser_code_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_theme',
            field=models.CharField(choices=[('grayscale', 'Grayscale'), ('pojoaque', 'Pojoaque'), ('codepen-embed', 'Codepen Embed'), ('atom-one-dark-reasonable', 'Atom One Dark Reasonable'), ('hybrid', 'Hybrid'), ('tokyo-night-dark', 'Tokyo Night Dark'), ('monokai-sublime', 'Monokai Sublime'), ('xcode', 'Xcode'), ('arduino-light', 'Arduino Light'), ('an-old-hope', 'An Old Hope'), ('ir-black', 'IR Black'), ('github-dark-dimmed', 'Github Dark Dimmed'), ('stackoverflow-light', 'Stackoverflow Light'), ('kimbie-light', 'Kimbie Light'), ('isbl-editor-dark', 'ISBL Editor Dark'), ('foundation', 'Foundation'), ('intellij-light', 'Intellij Light'), ('default', 'Default'), ('github', 'Github'), ('idea', 'Idea'), ('srcery', 'Srcery'), ('panda-syntax-dark', 'Panda Syntax Dark'), ('atom-one-dark', 'Atom One Dark'), ('tomorrow-night-bright', 'Tomorrow Night Bright'), ('lightfair', 'Lightfair'), ('paraiso-light', 'Paraiso Light'), ('shades-of-purple', 'Shades Of Purple'), ('gml', 'GML'), ('github-dark', 'Github Dark'), ('vs', 'VS'), ('qtcreator-light', 'Qtcreator Light'), ('obsidian', 'Obsidian'), ('paraiso-dark', 'Paraiso Dark'), ('tomorrow-night-blue', 'Tomorrow Night Blue'), ('gradient-light', 'Gradient Light'), ('purebasic', 'Purebasic'), ('nnfx-light', 'NNFX Light'), ('sunburst', 'Sunburst'), ('routeros', 'Routeros'), ('dark', 'Dark'), ('androidstudio', 'Android Studio'), ('atom-one-light', 'Atom One Light'), ('a11y-dark', 'A11y Dark'), ('nord', 'Nord'), ('nnfx-dark', 'NNFX Dark'), ('agate', 'Agate'), ('brown-paper', 'Brown Paper'), ('tokyo-night-light', 'Tokyo Night Light'), ('a11y-light', 'A11y Light'), ('far', 'Far'), ('magula', 'Magula'), ('mono-blue', 'Mono Blue'), ('arta', 'Arta'), ('isbl-editor-light', 'ISBL Editor Light'), ('qtcreator-dark', 'Qtcreator Dark'), ('felipec', 'Felipec'), ('panda-syntax-light', 'Panda Syntax Light'), ('night-owl', 'Night Owl'), ('xt256', 'XT256'), ('monokai', 'Monokai'), ('color-brewer', 'Color Brewer'), ('docco', 'Docco'), ('stackoverflow-dark', 'Stackoverflow Dark'), ('school-book', 'School Book'), ('lioshi', 'Lioshi'), ('gradient-dark', 'Gradient Dark'), ('devibeans', 'Devibeans'), ('kimbie-dark', 'Kimbie Dark'), ('vs2015', 'VS 2015'), ('googlecode', 'Google Code'), ('ascetic', 'Ascetic'), ('rainbow', 'Rainbow')], max_length=255),
        ),
    ]
